Algoritmo "Concatenação"


// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : James Fagno
// Data atual  : 15/07/2021
Var
// Seção de Declarações das variáveis 
      nome:caractere
      numero:real
      

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        escreval("Informe seu nome: ")
        leia(nome)
        escreval("Digite um numero: ")
        leia(numero)
                    escreval(nome, " : ", numero)
Fimalgoritmo