Algoritmo "operadores aritméticos"

// Descrição   : "Operações basicas"
// Autor(a)    : James Fagno
// Data atual  : 14/07/2021
Var
// Seção de Declarações das variáveis 
     resultado, valor01, valor02, valor03: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   valor01:= 20
   valor02:= 40
   valor03:= 20
   resultado:= ((valor01 + valor02)/ valor03) % 2
   escreval ("Resultado: ", resultado)

Fimalgoritmo