Algoritmo "Operadores relacionais"


// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/07/2021
Var
// Seção de Declarações das variáveis 
  nota01, nota02: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       nota01:= 10
       nota02:= 15
       se (nota01 >= nota02) entao

       escreval("nota01 é diferente") senão

        escreval("nota01 é igual")

        fimse

Fimalgoritmo