Algoritmo "Variáveis"
// Disciplina   : "Variáveis"
// Professor   : Curso online.
// Descrição   : Estudo para o uso de "variáveis".
// Autor(a)    : James Fagno
// Data atual  : 14/07/2021
Var
// Seção de Declarações das variáveis 
  Primeiro nome
  Segundo nome
  idade
  cidade
  endereco

  primeiroNome, segundoNome, cidade, endereco: caractere
  idade: inteiro
  

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo